name: Validate Wheelhouse

on:
  workflow_call:
    inputs:
      series:
        description: 'Matrix of ubuntu versions'
        default: "['bionic', 'focal', 'jammy']"
        required: false
        type: string
  
jobs:
  validate-wheelhouse:
    name: Validate Wheelhouse
    strategy:
      matrix:
        series: ${{ fromJson(inputs.series) }}
    runs-on: ubuntu-${{ matrix.series }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Install Dependencies
      run: |
        pip install tox
        sudo snap install charm --classic
    - name: Run validate-wheelhouse
      run: tox -vve validate-wheelhouse