name: Validate Wheelhouse

on:
  workflow_call:
    inputs:
      python:
        description: 'Matrix of python versions'
        default: "['3.6', '3.8', '3.10']"
        required: false
        type: string
  
jobs:
  validate-wheelhouse:
    name: Validate Wheelhouse
    strategy:
      matrix:
        python: ${{ fromJson(inputs.python) }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        pip install tox
        sudo snap install charm --classic
    - name: Run validate-wheelhouse
      run: tox -vve validate-wheelhouse
